let categoriesList = ["vegetables and greens", "herbs and spices", "dairy and eggs", "baking", "sugar and sweeteners", "fruits and berries", "oils and fats", "cheese", "condiments and relishes"];
let ingredientsList = 
[{"ingredientName":"garlic","category":"vegetables and greens"},
{"ingredientName":"onion","category":"vegetables and greens"},
{"ingredientName":"bell pepper","category":"vegetables and greens"},
{"ingredientName":"tomato","category":"vegetables and greens"},
{"ingredientName":"carrot","category":"vegetables and greens"},
{"ingredientName":"scallion","category":"vegetables and greens"},
{"ingredientName":"potato","category":"vegetables and greens"},
{"ingredientName":"ginger root","category":"vegetables and greens"},
{"ingredientName":"red onion","category":"vegetables and greens"},
{"ingredientName":"celery","category":"vegetables and greens"},
{"ingredientName":"mushroom","category":"vegetables and greens"},
{"ingredientName":"chili pepper","category":"vegetables and greens"},
{"ingredientName":"jalapeno","category":"vegetables and greens"},
{"ingredientName":"avocado","category":"vegetables and greens"},
{"ingredientName":"zucchini","category":"vegetables and greens"},
{"ingredientName":"shallot","category":"vegetables and greens"},
{"ingredientName":"cherry tomato","category":"vegetables and greens"},
{"ingredientName":"cucumber","category":"vegetables and greens"},
{"ingredientName":"sweet corn","category":"vegetables and greens"},
{"ingredientName":"spinach","category":"vegetables and greens"},
{"ingredientName":"sweet potato","category":"vegetables and greens"},
{"ingredientName":"broccoli","category":"vegetables and greens"},
{"ingredientName":"cabbage","category":"vegetables and greens"},
{"ingredientName":"baby greens","category":"vegetables and greens"},
{"ingredientName":"pumpkin","category":"vegetables and greens"},
{"ingredientName":"cauliflower","category":"vegetables and greens"},
{"ingredientName":"asparagus","category":"vegetables and greens"},
{"ingredientName":"arugula","category":"vegetables and greens"},
{"ingredientName":"kale","category":"vegetables and greens"},
{"ingredientName":"leek","category":"vegetables and greens"},
{"ingredientName":"lettuce","category":"vegetables and greens"},
{"ingredientName":"eggplant","category":"vegetables and greens"},
{"ingredientName":"beetroot","category":"vegetables and greens"},
{"ingredientName":"butternut squash","category":"vegetables and greens"},
{"ingredientName":"sweet onion","category":"vegetables and greens"},
{"ingredientName":"romaine","category":"vegetables and greens"},
{"ingredientName":"fennel","category":"vegetables and greens"},
{"ingredientName":"radish","category":"vegetables and greens"},
{"ingredientName":"squash","category":"vegetables and greens"},
{"ingredientName":"canned pumpkin","category":"vegetables and greens"},
{"ingredientName":"salad greens","category":"vegetables and greens"},
{"ingredientName":"horseradish","category":"vegetables and greens"},
{"ingredientName":"parsnip","category":"vegetables and greens"},
{"ingredientName":"bean sprouts","category":"vegetables and greens"},
{"ingredientName":"watercress","category":"vegetables and greens"},
{"ingredientName":"poblano pepper","category":"vegetables and greens"},
{"ingredientName":"bok choy","category":"vegetables and greens"},
{"ingredientName":"serrano pepper","category":"vegetables and greens"},
{"ingredientName":"sweet pepper","category":"vegetables and greens"},
{"ingredientName":"chard","category":"vegetables and greens"},
{"ingredientName":"pimiento","category":"vegetables and greens"},
{"ingredientName":"butter lettuce","category":"vegetables and greens"},
{"ingredientName":"green tomato","category":"vegetables and greens"},
{"ingredientName":"napa cabbage","category":"vegetables and greens"},
{"ingredientName":"spaghetti squash","category":"vegetables and greens"},
{"ingredientName":"celeriac","category":"vegetables and greens"},
{"ingredientName":"endive","category":"vegetables and greens"},
{"ingredientName":"turnip","category":"vegetables and greens"},
{"ingredientName":"broccoli rabe","category":"vegetables and greens"},
{"ingredientName":"radicchio","category":"vegetables and greens"},
{"ingredientName":"acorn squash","category":"vegetables and greens"},
{"ingredientName":"okra","category":"vegetables and greens"},
{"ingredientName":"plantain","category":"vegetables and greens"},
{"ingredientName":"pearl onion","category":"vegetables and greens"},
{"ingredientName":"jicama","category":"vegetables and greens"},
{"ingredientName":"habanero pepper","category":"vegetables and greens"},
{"ingredientName":"collard greens","category":"vegetables and greens"},
{"ingredientName":"baby corn","category":"vegetables and greens"},
{"ingredientName":"daikon","category":"vegetables and greens"},
{"ingredientName":"boston lettuce","category":"vegetables and greens"},
{"ingredientName":"rutabaga","category":"vegetables and greens"},
{"ingredientName":"ancho chili pepper","category":"vegetables and greens"},
{"ingredientName":"microgreens","category":"vegetables and greens"},
{"ingredientName":"kohlrabi","category":"vegetables and greens"},
{"ingredientName":"yam","category":"vegetables and greens"},
{"ingredientName":"delicata squash","category":"vegetables and greens"},
{"ingredientName":"frisee","category":"vegetables and greens"},
{"ingredientName":"galangal","category":"vegetables and greens"},
{"ingredientName":"anaheim pepper","category":"vegetables and greens"},
{"ingredientName":"broccoli slaw","category":"vegetables and greens"},
{"ingredientName":"cinnamon","category":"herbs and spices"},
{"ingredientName":"parsley","category":"herbs and spices"},
{"ingredientName":"cilantro","category":"herbs and spices"},
{"ingredientName":"basil","category":"herbs and spices"},
{"ingredientName":"cumin","category":"herbs and spices"},
{"ingredientName":"thyme","category":"herbs and spices"},
{"ingredientName":"garlic powder","category":"herbs and spices"},
{"ingredientName":"oregano","category":"herbs and spices"},
{"ingredientName":"paprika","category":"herbs and spices"},
{"ingredientName":"chili powder","category":"herbs and spices"},
{"ingredientName":"cayenne","category":"herbs and spices"},
{"ingredientName":"rosemary","category":"herbs and spices"},
{"ingredientName":"bay leaf","category":"herbs and spices"},
{"ingredientName":"nutmeg","category":"herbs and spices"},
{"ingredientName":"clove","category":"herbs and spices"},
{"ingredientName":"turmeric","category":"herbs and spices"},
{"ingredientName":"onion powder","category":"herbs and spices"},
{"ingredientName":"ginger powder","category":"herbs and spices"},
{"ingredientName":"chive","category":"herbs and spices"},
{"ingredientName":"dill","category":"herbs and spices"},
{"ingredientName":"ground nutmeg","category":"herbs and spices"},
{"ingredientName":"mint","category":"herbs and spices"},
{"ingredientName":"coriander powder","category":"herbs and spices"},
{"ingredientName":"fresh mint","category":"herbs and spices"},
{"ingredientName":"smoked paprika","category":"herbs and spices"},
{"ingredientName":"sage","category":"herbs and spices"},
{"ingredientName":"cardamom","category":"herbs and spices"},
{"ingredientName":"coriander","category":"herbs and spices"},
{"ingredientName":"allspice","category":"herbs and spices"},
{"ingredientName":"peppercorn","category":"herbs and spices"},
{"ingredientName":"white pepper","category":"herbs and spices"},
{"ingredientName":"mustard seed","category":"herbs and spices"},
{"ingredientName":"tarragon","category":"herbs and spices"},
{"ingredientName":"fennel seed","category":"herbs and spices"},
{"ingredientName":"curry leaves","category":"herbs and spices"},
{"ingredientName":"saffron","category":"herbs and spices"},
{"ingredientName":"chipotle","category":"herbs and spices"},
{"ingredientName":"star anise","category":"herbs and spices"},
{"ingredientName":"marjoram","category":"herbs and spices"},
{"ingredientName":"ground mustard","category":"herbs and spices"},
{"ingredientName":"asafoetida","category":"herbs and spices"},
{"ingredientName":"lemongrass","category":"herbs and spices"},
{"ingredientName":"chile powder","category":"herbs and spices"},
{"ingredientName":"celery seed","category":"herbs and spices"},
{"ingredientName":"tamarind","category":"herbs and spices"},
{"ingredientName":"sumac","category":"herbs and spices"},
{"ingredientName":"dried parsley flakes","category":"herbs and spices"},
{"ingredientName":"thai basil","category":"herbs and spices"},
{"ingredientName":"aniseed","category":"herbs and spices"},
{"ingredientName":"chervil","category":"herbs and spices"},
{"ingredientName":"lavender","category":"herbs and spices"},
{"ingredientName":"ancho chile powder","category":"herbs and spices"},
{"ingredientName":"mace","category":"herbs and spices"},
{"ingredientName":"carom seeds","category":"herbs and spices"},
{"ingredientName":"ancho chili powder","category":"herbs and spices"},
{"ingredientName":"lemon thyme","category":"herbs and spices"},
{"ingredientName":"lemon balm","category":"herbs and spices"},
{"ingredientName":"dill seed","category":"herbs and spices"},
{"ingredientName":"aleppo pepper","category":"herbs and spices"},
{"ingredientName":"achiote seeds","category":"herbs and spices"},
{"ingredientName":"sorrel","category":"herbs and spices"},
{"ingredientName":"hibiscus flowers","category":"herbs and spices"},
{"ingredientName":"gochugaru","category":"herbs and spices"},
{"ingredientName":"lemon basil","category":"herbs and spices"},
{"ingredientName":"alum powder","category":"herbs and spices"},
{"ingredientName":"butter","category":"dairy and eggs"},
{"ingredientName":"egg","category":"dairy and eggs"},
{"ingredientName":"milk","category":"dairy and eggs"},
{"ingredientName":"sour cream","category":"dairy and eggs"},
{"ingredientName":"heavy cream","category":"dairy and eggs"},
{"ingredientName":"whipped cream","category":"dairy and eggs"},
{"ingredientName":"yogurt","category":"dairy and eggs"},
{"ingredientName":"cream","category":"dairy and eggs"},
{"ingredientName":"buttermilk","category":"dairy and eggs"},
{"ingredientName":"greek yogurt","category":"dairy and eggs"},
{"ingredientName":"half and half","category":"dairy and eggs"},
{"ingredientName":"sweetened condensed milk","category":"dairy and eggs"},
{"ingredientName":"ice cream","category":"dairy and eggs"},
{"ingredientName":"evaporated milk","category":"dairy and eggs"},
{"ingredientName":"ghee","category":"dairy and eggs"},
{"ingredientName":"margarine","category":"dairy and eggs"},
{"ingredientName":"creme fraiche","category":"dairy and eggs"},
{"ingredientName":"condensed milk","category":"dairy and eggs"},
{"ingredientName":"frosting","category":"dairy and eggs"},
{"ingredientName":"milk powder","category":"dairy and eggs"},
{"ingredientName":"lemon curd","category":"dairy and eggs"},
{"ingredientName":"custard","category":"dairy and eggs"},
{"ingredientName":"whey protein","category":"dairy and eggs"},
{"ingredientName":"dulce de leche","category":"dairy and eggs"},
{"ingredientName":"chocolate milk","category":"dairy and eggs"},
{"ingredientName":"sherbet","category":"dairy and eggs"},
{"ingredientName":"frozen yogurt","category":"dairy and eggs"},
{"ingredientName":"buttermilk powder","category":"dairy and eggs"},
{"ingredientName":"sour milk","category":"dairy and eggs"},
{"ingredientName":"goat milk","category":"dairy and eggs"},
{"ingredientName":"flour","category":"baking"},
{"ingredientName":"vanilla","category":"baking"},
{"ingredientName":"baking powder","category":"baking"},
{"ingredientName":"baking soda","category":"baking"},
{"ingredientName":"cornstarch","category":"baking"},
{"ingredientName":"cocoa","category":"baking"},
{"ingredientName":"yeast","category":"baking"},
{"ingredientName":"whole-wheat flour","category":"baking"},
{"ingredientName":"self-raising flour","category":"baking"},
{"ingredientName":"panko","category":"baking"},
{"ingredientName":"almond flour","category":"baking"},
{"ingredientName":"almond extract","category":"baking"},
{"ingredientName":"baking chocolate","category":"baking"},
{"ingredientName":"shredded coconut","category":"baking"},
{"ingredientName":"food coloring","category":"baking"},
{"ingredientName":"cornmeal","category":"baking"},
{"ingredientName":"corn flour","category":"baking"},
{"ingredientName":"gelatin","category":"baking"},
{"ingredientName":"cake flour","category":"baking"},
{"ingredientName":"almond meal","category":"baking"},
{"ingredientName":"cream of tartar","category":"baking"},
{"ingredientName":"bread flour","category":"baking"},
{"ingredientName":"coconut flour","category":"baking"},
{"ingredientName":"baking mix","category":"baking"},
{"ingredientName":"rice flour","category":"baking"},
{"ingredientName":"desiccated coconut","category":"baking"},
{"ingredientName":"yellow cake mix","category":"baking"},
{"ingredientName":"gluten-free flour","category":"baking"},
{"ingredientName":"espresso powder","category":"baking"},
{"ingredientName":"oat flour","category":"baking"},
{"ingredientName":"xanthan gum","category":"baking"},
{"ingredientName":"peppermint extract","category":"baking"},
{"ingredientName":"lemon extract","category":"baking"},
{"ingredientName":"cassava flour","category":"baking"},
{"ingredientName":"bisquick","category":"baking"},
{"ingredientName":"spelt","category":"baking"},
{"ingredientName":"arrowroot flour","category":"baking"},
{"ingredientName":"brownie mix","category":"baking"},
{"ingredientName":"rose water","category":"baking"},
{"ingredientName":"potato starch","category":"baking"},
{"ingredientName":"coconut extract","category":"baking"},
{"ingredientName":"flaxseed meal","category":"baking"},
{"ingredientName":"chocolate cake mix","category":"baking"},
{"ingredientName":"edible flowers","category":"baking"},
{"ingredientName":"grits","category":"baking"},
{"ingredientName":"tapioca starch","category":"baking"},
{"ingredientName":"candy coating","category":"baking"},
{"ingredientName":"orange extract","category":"baking"},
{"ingredientName":"buckwheat flour","category":"baking"},
{"ingredientName":"brown rice flour","category":"baking"},
{"ingredientName":"cacao nibs","category":"baking"},
{"ingredientName":"chickpea flour","category":"baking"},
{"ingredientName":"rye flour","category":"baking"},
{"ingredientName":"semolina flour","category":"baking"},
{"ingredientName":"psyllium husk","category":"baking"},
{"ingredientName":"stuffing mix","category":"baking"},
{"ingredientName":"potato flakes","category":"baking"},
{"ingredientName":"muffin mix","category":"baking"},
{"ingredientName":"maple extract","category":"baking"},
{"ingredientName":"pancake mix","category":"baking"},
{"ingredientName":"marzipan","category":"baking"},
{"ingredientName":"orange blossom water","category":"baking"},
{"ingredientName":"millet flour","category":"baking"},
{"ingredientName":"cornbread mix","category":"baking"},
{"ingredientName":"baking chips","category":"baking"},
{"ingredientName":"instant lemon pudding","category":"baking"},
{"ingredientName":"sorghum flour","category":"baking"},
{"ingredientName":"sago","category":"baking"},
{"ingredientName":"hazelnut flour","category":"baking"},
{"ingredientName":"citric acid","category":"baking"},
{"ingredientName":"quinoa flour","category":"baking"},
{"ingredientName":"masa harina","category":"baking"},
{"ingredientName":"vital wheat gluten","category":"baking"},
{"ingredientName":"angel food cake mix","category":"baking"},
{"ingredientName":"seasoned flour","category":"baking"},
{"ingredientName":"tapioca pearls","category":"baking"},
{"ingredientName":"sugar","category":"sugar and sweeteners"},
{"ingredientName":"brown sugar","category":"sugar and sweeteners"},
{"ingredientName":"honey","category":"sugar and sweeteners"},
{"ingredientName":"maple syrup","category":"sugar and sweeteners"},
{"ingredientName":"corn syrup","category":"sugar and sweeteners"},
{"ingredientName":"coconut sugar","category":"sugar and sweeteners"},
{"ingredientName":"molasses","category":"sugar and sweeteners"},
{"ingredientName":"stevia","category":"sugar and sweeteners"},
{"ingredientName":"agave nectar","category":"sugar and sweeteners"},
{"ingredientName":"sugar syrup","category":"sugar and sweeteners"},
{"ingredientName":"erythritol","category":"sugar and sweeteners"},
{"ingredientName":"demerara sugar","category":"sugar and sweeteners"},
{"ingredientName":"vanilla sugar","category":"sugar and sweeteners"},
{"ingredientName":"raw sugar","category":"sugar and sweeteners"},
{"ingredientName":"golden syrup","category":"sugar and sweeteners"},
{"ingredientName":"chocolate syrup","category":"sugar and sweeteners"},
{"ingredientName":"cinnamon sugar","category":"sugar and sweeteners"},
{"ingredientName":"grenadine","category":"sugar and sweeteners"},
{"ingredientName":"coarse sugar","category":"sugar and sweeteners"},
{"ingredientName":"liquid stevia","category":"sugar and sweeteners"},
{"ingredientName":"pomegranate molasses","category":"sugar and sweeteners"},
{"ingredientName":"maple sugar","category":"sugar and sweeteners"},
{"ingredientName":"xylitol","category":"sugar and sweeteners"},
{"ingredientName":"caramel syrup","category":"sugar and sweeteners"},
{"ingredientName":"black treacle","category":"sugar and sweeteners"},
{"ingredientName":"pancake syrup","category":"sugar and sweeteners"},
{"ingredientName":"treacle","category":"sugar and sweeteners"},
{"ingredientName":"rice syrup","category":"sugar and sweeteners"},
{"ingredientName":"cane syrup","category":"sugar and sweeteners"},
{"ingredientName":"lemon","category":"fruits and berries"},
{"ingredientName":"lime","category":"fruits and berries"},
{"ingredientName":"apple","category":"fruits and berries"},
{"ingredientName":"orange","category":"fruits and berries"},
{"ingredientName":"banana","category":"fruits and berries"},
{"ingredientName":"strawberry","category":"fruits and berries"},
{"ingredientName":"blueberry","category":"fruits and berries"},
{"ingredientName":"raisins","category":"fruits and berries"},
{"ingredientName":"pineapple","category":"fruits and berries"},
{"ingredientName":"raspberry","category":"fruits and berries"},
{"ingredientName":"mango","category":"fruits and berries"},
{"ingredientName":"peach","category":"fruits and berries"},
{"ingredientName":"coconut","category":"fruits and berries"},
{"ingredientName":"craisins","category":"fruits and berries"},
{"ingredientName":"pear","category":"fruits and berries"},
{"ingredientName":"date","category":"fruits and berries"},
{"ingredientName":"cherry","category":"fruits and berries"},
{"ingredientName":"pomegranate","category":"fruits and berries"},
{"ingredientName":"grape","category":"fruits and berries"},
{"ingredientName":"blackberry","category":"fruits and berries"},
{"ingredientName":"watermelon","category":"fruits and berries"},
{"ingredientName":"berry mix","category":"fruits and berries"},
{"ingredientName":"rhubarb","category":"fruits and berries"},
{"ingredientName":"dried apricot","category":"fruits and berries"},
{"ingredientName":"kiwi","category":"fruits and berries"},
{"ingredientName":"plum","category":"fruits and berries"},
{"ingredientName":"maraschino cherry","category":"fruits and berries"},
{"ingredientName":"grapefruit","category":"fruits and berries"},
{"ingredientName":"fig","category":"fruits and berries"},
{"ingredientName":"apricot","category":"fruits and berries"},
{"ingredientName":"mandarin","category":"fruits and berries"},
{"ingredientName":"currant","category":"fruits and berries"},
{"ingredientName":"canned pineapple","category":"fruits and berries"},
{"ingredientName":"sultanas","category":"fruits and berries"},
{"ingredientName":"passion fruit","category":"fruits and berries"},
{"ingredientName":"papaya","category":"fruits and berries"},
{"ingredientName":"cantaloupe","category":"fruits and berries"},
{"ingredientName":"prunes","category":"fruits and berries"},
{"ingredientName":"nectarine","category":"fruits and berries"},
{"ingredientName":"kaffir lime leaves","category":"fruits and berries"},
{"ingredientName":"meyer lemon","category":"fruits and berries"},
{"ingredientName":"honeydew melon","category":"fruits and berries"},
{"ingredientName":"dried fruit","category":"fruits and berries"},
{"ingredientName":"clementine","category":"fruits and berries"},
{"ingredientName":"dried mango","category":"fruits and berries"},
{"ingredientName":"melon","category":"fruits and berries"},
{"ingredientName":"tangerine","category":"fruits and berries"},
{"ingredientName":"persimmon","category":"fruits and berries"},
{"ingredientName":"fruit cocktail","category":"fruits and berries"},
{"ingredientName":"quince","category":"fruits and berries"},
{"ingredientName":"jackfruit","category":"fruits and berries"},
{"ingredientName":"kumquat","category":"fruits and berries"},
{"ingredientName":"guava","category":"fruits and berries"},
{"ingredientName":"lychee","category":"fruits and berries"},
{"ingredientName":"dragon fruit","category":"fruits and berries"},
{"ingredientName":"asian pear","category":"fruits and berries"},
{"ingredientName":"star fruit","category":"fruits and berries"},
{"ingredientName":"olive oil","category":"oils and fats"},
{"ingredientName":"vegetable oil","category":"oils and fats"},
{"ingredientName":"extra virgin olive oil","category":"oils and fats"},
{"ingredientName":"canola oil","category":"oils and fats"},
{"ingredientName":"coconut oil","category":"oils and fats"},
{"ingredientName":"sesame oil","category":"oils and fats"},
{"ingredientName":"frying oil","category":"oils and fats"},
{"ingredientName":"avocado oil","category":"oils and fats"},
{"ingredientName":"sunflower oil","category":"oils and fats"},
{"ingredientName":"peanut oil","category":"oils and fats"},
{"ingredientName":"grapeseed oil","category":"oils and fats"},
{"ingredientName":"corn oil","category":"oils and fats"},
{"ingredientName":"chili oil","category":"oils and fats"},
{"ingredientName":"walnut oil","category":"oils and fats"},
{"ingredientName":"mustard oil","category":"oils and fats"},
{"ingredientName":"truffle oil","category":"oils and fats"},
{"ingredientName":"safflower oil","category":"oils and fats"},
{"ingredientName":"salad oil","category":"oils and fats"},
{"ingredientName":"rice bran oil","category":"oils and fats"},
{"ingredientName":"duck fat","category":"oils and fats"},
{"ingredientName":"garlic oil","category":"oils and fats"},
{"ingredientName":"flaxseed oil","category":"oils and fats"},
{"ingredientName":"hazelnut oil","category":"oils and fats"},
{"ingredientName":"lemon oil","category":"oils and fats"},
{"ingredientName":"almond oil","category":"oils and fats"},
{"ingredientName":"palm oil","category":"oils and fats"},
{"ingredientName":"schmaltz","category":"oils and fats"},
{"ingredientName":"goose fat","category":"oils and fats"},
{"ingredientName":"basil oil","category":"oils and fats"},
{"ingredientName":"pistachio oil","category":"oils and fats"},
{"ingredientName":"parmesan","category":"cheese"},
{"ingredientName":"cream cheese","category":"cheese"},
{"ingredientName":"cheddar","category":"cheese"},
{"ingredientName":"mozzarella","category":"cheese"},
{"ingredientName":"feta","category":"cheese"},
{"ingredientName":"ricotta","category":"cheese"},
{"ingredientName":"sharp cheddar","category":"cheese"},
{"ingredientName":"blue cheese","category":"cheese"},
{"ingredientName":"monterey jack","category":"cheese"},
{"ingredientName":"goat cheese","category":"cheese"},
{"ingredientName":"fresh mozzarella","category":"cheese"},
{"ingredientName":"swiss cheese","category":"cheese"},
{"ingredientName":"pecorino","category":"cheese"},
{"ingredientName":"mascarpone","category":"cheese"},
{"ingredientName":"gruyere","category":"cheese"},
{"ingredientName":"american cheese","category":"cheese"},
{"ingredientName":"cottage cheese","category":"cheese"},
{"ingredientName":"provolone","category":"cheese"},
{"ingredientName":"pepper jack","category":"cheese"},
{"ingredientName":"brie","category":"cheese"},
{"ingredientName":"gouda","category":"cheese"},
{"ingredientName":"paneer","category":"cheese"},
{"ingredientName":"queso fresco","category":"cheese"},
{"ingredientName":"quark","category":"cheese"},
{"ingredientName":"asiago","category":"cheese"},
{"ingredientName":"halloumi","category":"cheese"},
{"ingredientName":"chevre","category":"cheese"},
{"ingredientName":"manchego","category":"cheese"},
{"ingredientName":"italian cheese blend","category":"cheese"},
{"ingredientName":"burrata","category":"cheese"},
{"ingredientName":"havarti","category":"cheese"},
{"ingredientName":"soft cheese","category":"cheese"},
{"ingredientName":"camembert","category":"cheese"},
{"ingredientName":"stilton","category":"cheese"},
{"ingredientName":"jarlsberg cheese","category":"cheese"},
{"ingredientName":"soy sauce","category":"condiments and relishes"},
{"ingredientName":"dijon mustard","category":"condiments and relishes"},
{"ingredientName":"worcestershire","category":"condiments and relishes"},
{"ingredientName":"hot sauce","category":"condiments and relishes"},
{"ingredientName":"mustard","category":"condiments and relishes"},
{"ingredientName":"ketchup","category":"condiments and relishes"},
{"ingredientName":"capers","category":"condiments and relishes"},
{"ingredientName":"fish sauce","category":"condiments and relishes"},
{"ingredientName":"green olives","category":"condiments and relishes"},
{"ingredientName":"black olives","category":"condiments and relishes"},
{"ingredientName":"bbq sauce","category":"condiments and relishes"},
{"ingredientName":"sun dried tomato","category":"condiments and relishes"},
{"ingredientName":"apple sauce","category":"condiments and relishes"},
{"ingredientName":"sriracha","category":"condiments and relishes"},
{"ingredientName":"pickle","category":"condiments and relishes"},
{"ingredientName":"kalamata olives","category":"condiments and relishes"},
{"ingredientName":"chipotle in adobo","category":"condiments and relishes"},
{"ingredientName":"chili sauce","category":"condiments and relishes"},
{"ingredientName":"wholegrain mustard","category":"condiments and relishes"},
{"ingredientName":"chili paste","category":"condiments and relishes"},
{"ingredientName":"ginger-garlic paste","category":"condiments and relishes"},
{"ingredientName":"teriyaki sauce","category":"condiments and relishes"}];